require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.nvtheme"
require "user.autocmp"
require "user.lngsrvp"
require "user.tlscope"
require "user.treestr"
require "user.atopirs"
require "user.vimtree"
require "user.lualine"
require "user.comment"
require "user.gitsign"

Tabs= require "user.fncions"
Tabs.setup()
